[project]
name = "algomancy-tutorial"
version = "0.1.0"
description = "Basic exploration of algomancy library"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "algomancy>=0.3.19",
]
