[project]
name = "Algomancy"
version = "0.3.1"
description = "A dashboarding framework for visualizing performances of algorithms or simulations in various scenarios."
requires-python = ">=3.14"
dependencies = [
    "dash>=3.2.0",
    "dash-auth>=2.3.0",
    "dash-bootstrap-components>=2.0.3",
    "dash-daq>=0.6.0",
    "dash-iconify>=0.1.2",
    "openpyxl>=3.1.5",
    "pandas>=2.3.1",
    "prek>=0.2.1",
    "pytest>=8.4.2",
    "ruff>=0.13.1",
    "strenum>=0.4.15",
    "tabulate>=0.9.0",
    "waitress>=3.0.2",
    "wheel>=0.45.1",
]
authors = [
    {name = "Pepijn Wissing", email = "pepijn.wissing@cqm.nl"},
    {name = "Bart Post", email = "bart.post@cqm.nl"}
]
maintainers = [
    {name = "Pepijn Wissing", email = "pepijn.wissing@cqm.nl"},
    {name = "Bart Post", email = "bart.post@cqm.nl"}
]
readme = "README.md"
license = {text = "Restricted"}
keywords = ["visualization", "algorithm", "simulation", "scenario"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = [
    "algomancy",
    "algomancy.components",
    "algomancy.components.admin_page",
    "algomancy.components.data_page",
    "algomancy.components.home_page",
    "algomancy.components.overview_page",
    "algomancy.components.compare_page",
    "algomancy.components.scenario_page",
    "algomancy.contentcreatorlibrary",
    "algomancy.dashboardlogger",
    "algomancy.dataengine",
    "algomancy.scenarioengine",
]
