[build-system]
build-backend = "uv_build"
requires = ["uv_build>=0.9.6,<0.10.0"]

[project]
authors = [
  {email = "pepijn.wissing@cqm.nl", name = "Pepijn Wissing"},
  {email = "bart.post@cqm.nl", name = "Bart Post"}
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]
dependencies = [
  "dash>=3.2.0",
  "dash-auth>=2.3.0",
  "dash-bootstrap-components>=2.0.3",
  "dash-daq>=0.6.0",
  "dash-iconify>=0.1.2",
  "openpyxl>=3.1.5",
  "pandas>=2.3.1",
  "pytest>=8.4.2",
  "ruff>=0.13.1",
  "strenum>=0.4.15",
  "tabulate>=0.9.0",
  "waitress>=3.0.2",
  "wheel>=0.45.1",
  "uv_build>=0.9.6,<0.10.0",
  "algomancy-content",
  "algomancy-data",
  "algomancy-scenario",
  "algomancy-utils",
  "algomancy-gui",
  "prek>=0.2.19",
  "pyrefly>=0.45.2",
  "basedpyright>=1.36.0"
]
description = "A dashboarding framework for visualizing performances of algorithms or simulations in various scenarios."
keywords = ["visualization", "algorithm", "simulation", "scenario"]
license = {text = "Restricted"}
maintainers = [
  {email = "pepijn.wissing@cqm.nl", name = "Pepijn Wissing"},
  {email = "bart.post@cqm.nl", name = "Bart Post"}
]
name = "Algomancy"
readme = "README.md"
requires-python = ">=3.14"
version = "0.3.2"

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.uv.sources]
algomancy-content = {workspace = true}
algomancy-data = {workspace = true}
algomancy-gui = {workspace = true}
algomancy-scenario = {workspace = true}
algomancy-utils = {workspace = true}

[tool.uv.workspace]
members = [
  "packages/algomancy-content",
  "packages/algomancy-gui",
  "packages/algomancy-utils",
  "packages/algomancy-data",
  "packages/algomancy-scenario"
]
