[project]
name = "Algomancy"
version = "0.2.1"
description = "A dashboarding framework for visualizing performances of algorithms or simulations in various scenarios."
requires-python = ">=3.11"
dependencies = [
    "dash>=3.2.0",
    "dash-auth>=2.3.0",
    "dash-bootstrap-components>=2.0.3",
    "dash-extensions>=2.0.4",
    "dash-iconify>=0.1.2",
    "diskcache>=5.6.3",
    "fastparquet>=2024.11.0",
    "openpyxl>=3.1.5",
    "pandas>=2.3.1",
    "prek>=0.2.1",
    "python-dotenv>=1.1.1",
    "ruff>=0.13.1",
    "strenum>=0.4.15",
    "tabulate>=0.9.0",
    "wheel>=0.45.1"
]
authors = [
    {name = "Pepijn Wissing", email = "pepijn.wissing@cqm.nl"},
    {name = "Bart Post", email = "bart.post@cqm.nl"}
]
maintainers = [
    {name = "Pepijn Wissing", email = "pepijn.wissing@cqm.nl"},
    {name = "Bart Post", email = "bart.post@cqm.nl"}
]
readme = "README.md"
license = {text = "Restricted"}
keywords = ["visualization", "algorithm", "simulation", "scenario"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["algomancy"]
