[project]
name = "algomancy-data"
version = "0.1.0"
description = "Data management model for the Algomancy library"
readme = "README.md"
authors = [
    { name = "Pepijn Wissing", email = "Wsg@cqm.nl" }
]
requires-python = ">=3.14"
dependencies = [
    "pandas",
]

[build-system]
requires = ["uv_build>=0.9.6,<0.10.0"]
build-backend = "uv_build"

