[project]
name = "algomancy-data"
version = "0.3.18"
description = "Data management model for the Algomancy library"
readme = "README.md"
authors = [
    { name = "Pepijn Wissing", email = "Wsg@cqm.nl" }
]
requires-python = ">=3.14"
dependencies = [
    "pandas",
    "openpyxl>=3.1.5",
    "algomancy-utils",
    "strenum>=0.4.15"
]

[build-system]
requires = ["uv_build>=0.9.6,<0.10.0"]
build-backend = "uv_build"

