[project]
name = "algomancy-scenario"
version = "0.3.15"
description = "Scenario management model for the Algomancy library"
readme = "README.md"
authors = [
    { name = "Pepijn Wissing", email = "Wsg@cqm.nl" }
]
requires-python = ">=3.14"
dependencies = [
    "algomancy-utils",
    "algomancy-data",
]

[build-system]
requires = ["uv_build>=0.9.6,<0.10.0"]
build-backend = "uv_build"
