[project]
name = "algomancy-content"
version = "0.3.20"
description = "Placeholder content for quick start to the Algomancy library"
readme = "README.md"
authors = [
    { name = "Pepijn Wissing", email = "Wsg@cqm.nl" }
]
requires-python = ">=3.14"
dependencies = [
    "algomancy-data",
    "algomancy-scenario",
    "dash",
    "dash-bootstrap-components",
    "dash-daq",
    "pandas",
]

[build-system]
requires = ["uv_build>=0.9.6,<0.10.0"]
build-backend = "uv_build"
