[project]
name = "algomancy-gui"
version = "0.4.1"
description = "Dash components for the Algomancy library"
readme = "README.md"
authors = [
    { name = "Pepijn Wissing", email = "Wsg@cqm.nl" }
]
requires-python = ">=3.14"
dependencies = [
    "dash",
    "dash_bootstrap_components",
    "dash-auth >= 2.3.0",
    "algomancy-data",
    "algomancy-scenario",
    "algomancy-content",
    "algomancy-utils",
    "waitress>=3.0.2",
    "strenum>=0.4.15",
]

[build-system]
requires = ["uv_build>=0.9.6,<0.10.0"]
build-backend = "uv_build"
