[project]
name = "algomancy-utils"
version = "0.3.12"
description = "Miscellaneous modules used in the Algomancy library"
readme = "README.md"
authors = [
    { name = "Pepijn Wissing", email = "Wsg@cqm.nl" }
]
requires-python = ">=3.14"
dependencies = []

[build-system]
requires = ["uv_build>=0.9.6,<0.10.0"]
build-backend = "uv_build"
